// This file is automatically generated by qtc from "notify_api.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// // Code generated. DO NOT EDIT.

//line notify_api.qtpl:2
package delphirpc

//line notify_api.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line notify_api.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line notify_api.qtpl:4
func (x *NotifyServicesSrc) StreamGoFile(qw422016 *qt422016.Writer) {
	//line notify_api.qtpl:4
	qw422016.N().S(`
package notify

import (
	"github.com/fpawel/elco/pkg/copydata"
	`)
	//line notify_api.qtpl:9
	for imp := range x.goImports {
		//line notify_api.qtpl:9
		qw422016.N().S(`"`)
		//line notify_api.qtpl:9
		qw422016.E().S(imp)
		//line notify_api.qtpl:9
		qw422016.N().S(`"
    `)
		//line notify_api.qtpl:10
	}
	//line notify_api.qtpl:10
	qw422016.N().S(`
)

type msg int

type W = *copydata.NotifyWindow

const (
    msg`)
	//line notify_api.qtpl:18
	qw422016.E().S(x.services[0].serviceName)
	//line notify_api.qtpl:18
	qw422016.N().S(` msg = iota
    `)
	//line notify_api.qtpl:19
	for _, m := range x.services[1:] {
		//line notify_api.qtpl:19
		qw422016.N().S(`msg`)
		//line notify_api.qtpl:19
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:19
		qw422016.N().S(`
    `)
		//line notify_api.qtpl:20
	}
	//line notify_api.qtpl:20
	qw422016.N().S(`
)

var
    msgName = map[msg]string{
        `)
	//line notify_api.qtpl:25
	for _, m := range x.services {
		//line notify_api.qtpl:25
		qw422016.N().S(`msg`)
		//line notify_api.qtpl:25
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:25
		qw422016.N().S(`:"`)
		//line notify_api.qtpl:25
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:25
		qw422016.N().S(`",
        `)
		//line notify_api.qtpl:26
	}
	//line notify_api.qtpl:26
	qw422016.N().S(`
    }

func FormatMsg(msgCode uintptr) string {
    s,_ := msgName[msg(msgCode)]
    return s
}

`)
	//line notify_api.qtpl:34
	for _, m := range x.services {
		//line notify_api.qtpl:34
		qw422016.N().S(`func `)
		//line notify_api.qtpl:34
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:34
		qw422016.N().S(`(w W, arg `)
		//line notify_api.qtpl:34
		qw422016.E().S(m.goType)
		//line notify_api.qtpl:34
		qw422016.N().S(`) {
    w.`)
		//line notify_api.qtpl:35
		qw422016.E().S(m.notifyFunc)
		//line notify_api.qtpl:35
		qw422016.N().S(`( uintptr(msg`)
		//line notify_api.qtpl:35
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:35
		qw422016.N().S(`), `)
		//line notify_api.qtpl:35
		qw422016.N().S(m.instructionArg)
		//line notify_api.qtpl:35
		qw422016.N().S(` )
}
`)
		//line notify_api.qtpl:37
		if m.notifyFunc == "NotifyStr" {
			//line notify_api.qtpl:37
			qw422016.N().S(`func `)
			//line notify_api.qtpl:37
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:37
			qw422016.N().S(`f(w W, format string, a ...interface{}) {
    w.Notifyf( uintptr(msg`)
			//line notify_api.qtpl:38
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:38
			qw422016.N().S(`), format, a... )
}`)
			//line notify_api.qtpl:39
		}
		//line notify_api.qtpl:39
		qw422016.N().S(`
`)
		//line notify_api.qtpl:40
	}
	//line notify_api.qtpl:40
	qw422016.N().S(`



`)
//line notify_api.qtpl:44
}

//line notify_api.qtpl:44
func (x *NotifyServicesSrc) WriteGoFile(qq422016 qtio422016.Writer) {
	//line notify_api.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line notify_api.qtpl:44
	x.StreamGoFile(qw422016)
	//line notify_api.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line notify_api.qtpl:44
}

//line notify_api.qtpl:44
func (x *NotifyServicesSrc) GoFile() string {
	//line notify_api.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
	//line notify_api.qtpl:44
	x.WriteGoFile(qb422016)
	//line notify_api.qtpl:44
	qs422016 := string(qb422016.B)
	//line notify_api.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
	//line notify_api.qtpl:44
	return qs422016
//line notify_api.qtpl:44
}
