// This file is automatically generated by qtc from "notify_api.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// // Code generated. DO NOT EDIT.

//line notify_api.qtpl:2
package delphirpc

//line notify_api.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line notify_api.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line notify_api.qtpl:4
func (x *NotifyServicesSrc) StreamGoFile(qw422016 *qt422016.Writer) {
	//line notify_api.qtpl:4
	qw422016.N().S(`
package notify

import (
	`)
	//line notify_api.qtpl:8
	for imp := range x.goImports {
		//line notify_api.qtpl:8
		qw422016.N().S(`"`)
		//line notify_api.qtpl:8
		qw422016.E().S(imp)
		//line notify_api.qtpl:8
		qw422016.N().S(`"
    `)
		//line notify_api.qtpl:9
	}
	//line notify_api.qtpl:9
	qw422016.N().S(`
)

type msg int

const (
    msg`)
	//line notify_api.qtpl:15
	qw422016.E().S(x.services[0].serviceName)
	//line notify_api.qtpl:15
	qw422016.N().S(` msg = iota
    `)
	//line notify_api.qtpl:16
	for _, m := range x.services[1:] {
		//line notify_api.qtpl:16
		qw422016.N().S(`msg`)
		//line notify_api.qtpl:16
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:16
		qw422016.N().S(`
    `)
		//line notify_api.qtpl:17
	}
	//line notify_api.qtpl:17
	qw422016.N().S(`
)

`)
	//line notify_api.qtpl:20
	for _, m := range x.services {
		//line notify_api.qtpl:20
		qw422016.N().S(`func `)
		//line notify_api.qtpl:20
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:20
		qw422016.N().S(`(log *structlog.Logger, arg `)
		//line notify_api.qtpl:20
		qw422016.E().S(m.goType)
		//line notify_api.qtpl:20
		qw422016.N().S(`) {
    if log != nil {
        msg`)
		//line notify_api.qtpl:22
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:22
		qw422016.N().S(`.Log(log)(peer.WindowClassName + ": `)
		//line notify_api.qtpl:22
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:22
		qw422016.N().S(`: "+ fmt.Sprintf("%+v",arg), "MSG", msg`)
		//line notify_api.qtpl:22
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:22
		qw422016.N().S(`, )
    }
    go peer.`)
		//line notify_api.qtpl:24
		qw422016.E().S(m.notifyFunc)
		//line notify_api.qtpl:24
		qw422016.N().S(`( uintptr(msg`)
		//line notify_api.qtpl:24
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:24
		qw422016.N().S(`), `)
		//line notify_api.qtpl:24
		qw422016.N().S(m.instructionArg)
		//line notify_api.qtpl:24
		qw422016.N().S(` )
}
func `)
		//line notify_api.qtpl:26
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:26
		qw422016.N().S(`Sync(log *structlog.Logger, arg `)
		//line notify_api.qtpl:26
		qw422016.E().S(m.goType)
		//line notify_api.qtpl:26
		qw422016.N().S(`) {
    if log != nil {
        msg`)
		//line notify_api.qtpl:28
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:28
		qw422016.N().S(`.Log(log)(peer.WindowClassName + ": `)
		//line notify_api.qtpl:28
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:28
		qw422016.N().S(`: "+ fmt.Sprintf("%+v",arg), "MSG", msg`)
		//line notify_api.qtpl:28
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:28
		qw422016.N().S(`, )
    }
    peer.`)
		//line notify_api.qtpl:30
		qw422016.E().S(m.notifyFunc)
		//line notify_api.qtpl:30
		qw422016.N().S(`( uintptr(msg`)
		//line notify_api.qtpl:30
		qw422016.E().S(m.serviceName)
		//line notify_api.qtpl:30
		qw422016.N().S(`), `)
		//line notify_api.qtpl:30
		qw422016.N().S(m.instructionArg)
		//line notify_api.qtpl:30
		qw422016.N().S(` )
}
`)
		//line notify_api.qtpl:32
		if m.notifyFunc == "NotifyStr" {
			//line notify_api.qtpl:32
			qw422016.N().S(`
func `)
			//line notify_api.qtpl:33
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:33
			qw422016.N().S(`f(log *structlog.Logger, format string, a ...interface{}) {
    if log != nil {
        msg`)
			//line notify_api.qtpl:35
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:35
			qw422016.N().S(`.Log(log)(peer.WindowClassName + ": `)
			//line notify_api.qtpl:35
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:35
			qw422016.N().S(`: " + fmt.Sprintf(format,a...), "MSG", msg`)
			//line notify_api.qtpl:35
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:35
			qw422016.N().S(`, )
    }
    go peer.Notifyf( uintptr(msg`)
			//line notify_api.qtpl:37
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:37
			qw422016.N().S(`), format, a... )
}
func `)
			//line notify_api.qtpl:39
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:39
			qw422016.N().S(`Syncf(log *structlog.Logger, format string, a ...interface{}) {
    if log != nil {
        msg`)
			//line notify_api.qtpl:41
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:41
			qw422016.N().S(`.Log(log)(peer.WindowClassName + ": `)
			//line notify_api.qtpl:41
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:41
			qw422016.N().S(`: " + fmt.Sprintf(format,a...), "MSG", msg`)
			//line notify_api.qtpl:41
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:41
			qw422016.N().S(`, )
    }
    peer.Notifyf( uintptr(msg`)
			//line notify_api.qtpl:43
			qw422016.E().S(m.serviceName)
			//line notify_api.qtpl:43
			qw422016.N().S(`), format, a... )
}`)
			//line notify_api.qtpl:44
		}
		//line notify_api.qtpl:44
		qw422016.N().S(`
`)
		//line notify_api.qtpl:45
	}
	//line notify_api.qtpl:45
	qw422016.N().S(`



`)
//line notify_api.qtpl:49
}

//line notify_api.qtpl:49
func (x *NotifyServicesSrc) WriteGoFile(qq422016 qtio422016.Writer) {
	//line notify_api.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line notify_api.qtpl:49
	x.StreamGoFile(qw422016)
	//line notify_api.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line notify_api.qtpl:49
}

//line notify_api.qtpl:49
func (x *NotifyServicesSrc) GoFile() string {
	//line notify_api.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
	//line notify_api.qtpl:49
	x.WriteGoFile(qb422016)
	//line notify_api.qtpl:49
	qs422016 := string(qb422016.B)
	//line notify_api.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
	//line notify_api.qtpl:49
	return qs422016
//line notify_api.qtpl:49
}
