// This file is automatically generated by qtc from "types.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line types.qtpl:1
package delphirpc

//line types.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line types.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line types.qtpl:4
func streamdeclInterfaceClass(qw422016 *qt422016.Writer, t typeInfo) {
	//line types.qtpl:4
	qw422016.N().S(` 
    `)
	//line types.qtpl:5
	qw422016.E().S(t.name)
	//line types.qtpl:5
	qw422016.N().S(` = record
    public 
        `)
	//line types.qtpl:7
	for _, f := range t.fields {
		//line types.qtpl:7
		if f.name == "String" {
			//line types.qtpl:7
			qw422016.N().S(` [BsonElement('String')]Str`)
			//line types.qtpl:7
		} else {
			//line types.qtpl:7
			qw422016.E().S(f.name)
			//line types.qtpl:7
		}
		//line types.qtpl:7
		qw422016.N().S(` : `)
		//line types.qtpl:7
		qw422016.N().S(f.typeName)
		//line types.qtpl:7
		qw422016.N().S(`;
        `)
		//line types.qtpl:8
	}
	//line types.qtpl:8
	qw422016.N().S(`
    end;
`)
//line types.qtpl:10
}

//line types.qtpl:10
func writedeclInterfaceClass(qq422016 qtio422016.Writer, t typeInfo) {
	//line types.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line types.qtpl:10
	streamdeclInterfaceClass(qw422016, t)
	//line types.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line types.qtpl:10
}

//line types.qtpl:10
func declInterfaceClass(t typeInfo) string {
	//line types.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
	//line types.qtpl:10
	writedeclInterfaceClass(qb422016, t)
	//line types.qtpl:10
	qs422016 := string(qb422016.B)
	//line types.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
	//line types.qtpl:10
	return qs422016
//line types.qtpl:10
}

//line types.qtpl:12
func (x *TypesSrc) StreamUnit(qw422016 *qt422016.Writer) {
	//line types.qtpl:12
	qw422016.N().S(`
unit `)
	//line types.qtpl:13
	qw422016.E().S(x.unitName)
	//line types.qtpl:13
	qw422016.N().S(`;

interface

`)
	//line types.qtpl:17
	qw422016.E().S(uses(x.interfaceUses))
	//line types.qtpl:17
	qw422016.N().S(`

type
    `)
	//line types.qtpl:20
	for _, t := range x.types {
		//line types.qtpl:20
		qw422016.N().S(declInterfaceClass(t))
		//line types.qtpl:20
	}
	//line types.qtpl:20
	qw422016.N().S(`

implementation 

`)
	//line types.qtpl:24
	qw422016.E().S(uses(x.implUses))
	//line types.qtpl:24
	qw422016.N().S(`

end.`)
//line types.qtpl:26
}

//line types.qtpl:26
func (x *TypesSrc) WriteUnit(qq422016 qtio422016.Writer) {
	//line types.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line types.qtpl:26
	x.StreamUnit(qw422016)
	//line types.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line types.qtpl:26
}

//line types.qtpl:26
func (x *TypesSrc) Unit() string {
	//line types.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
	//line types.qtpl:26
	x.WriteUnit(qb422016)
	//line types.qtpl:26
	qs422016 := string(qb422016.B)
	//line types.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
	//line types.qtpl:26
	return qs422016
//line types.qtpl:26
}
