// Code generated by "esc -o img.go -pkg=daemon img"; DO NOT EDIT.

package daemon

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return []os.FileInfo(fis[0:limit]), nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/img/appicon.ico": {
		name:    "appicon.ico",
		local:   "img/appicon.ico",
		size:    4286,
		modtime: 1549138684,
		compressed: `
H4sIAAAAAAAC/8RXS1CbVRS+QK2Or9I6rY5Wjba11YU66kIdFx2dOnWhjlZXuuj4rLpwxo3jqAsXXfjY
+OhCh5cF8k4IhAiUhgIJKe/yKKEFjYTQhFdIgCSUR/I55/wkJfQPEB71ztyB/Ln/+c6555zvfBEiQ2QI
hYL+KoQ6W4g9QohDQgiFEOKwkJ7zyhZi3+PSji+sYUWjc/AHLqDL+T2qao9CU7oXBZqbkKcSvOl/tek+
VJ47go6ekxjzt2AhehUbXYQ7PFoPW+Nxtp+vzkSuUiB3EXf5pu/yVJlQldyDOsc78A5bEY3Orgs7FB5E
Y9vnKDbsQs4KmLJ+qAS/U6jfgYaWE5gKudLCHhlrgPnMs4vxbGyTjdLKp+AdqVkT9hXfGejM+zYFe6kP
mtIH4B4qXSVuB3Tm/ZuKvdyHVPcQCntQXv38lmAn5+JpTE3/k4Qdiy2gqf2LLcVe6gPVJPXW0norNu5O
q8Y3sov02dyb8dgbmj9aNfbcRH+vHt9q56g3ax3vMjcEghehLVOkfIee56u3QWnczbxXZNjJHLP0fNy3
Qt3tzFPEPwWam1e0qTLdyzzZc/lnti/vawbKq59Dvyuf/ZwODWB8og3dvT9yj8ZtKUvuRkvHlxgetTHX
BKcuwz1UAqv9GPshbzsTnT0nYbW9KesnPaPvwpErnKfZ2QCmQ27Mz4f4s2+kdvFO7ofHW0GZ5JoKR4YQ
mRlGLBbF/EIYFy5+J+sD2a889zL05Y9ch0+fdeaHEZh0MpZrUIuyqmf4/itqXsSApwRtnV/jtPZWOPt+
S/C1rek9ziXZbOv6BnNzU+xDjf0t2RgpV4W6O2R9c7R8wnYnAl0cY07xtdo6rb2Nc6YvP8C8QbE2NH8s
zYlE/W1L+DbgMaJAs/06HJqbNNPk8J19v/K7l/7+XbYvc/j+jnANU4705gNJMZK/1fWvsW+BYA/nSs5O
vjpLFp/qUsL/I2UPVda8xHOe8ZflkfCttmNcF1S7qfAL9XfK4tubP5DuP9gNTZki+f4pZ+osrpHp0L+I
IQZHy4mkM1Rz/a4C6f4H9Ul65dr9b4eh/KBs/dGs8Ac6+H23xwTL2RegN+/H2frX4fFaYG96n++uq/cH
PkN1Tz6QPVPFE+ju/QkLCzPcL3I9RndBdVVjfztl/1XVvpLQDmSH+iquq2iOERcpjXvgcmuZR2nPXB3F
7Fxg8Z1ptHd9K1t7kv2jcPadSsk/5KOp4kk4+35hrgpOXsLo+HnmH6PlsYSdIv1OnilD3gruWX+gEy63
CtX1r8piS3WXyXoyONnLeVyJK4mrivQ7OFapXzNkc/an9hauM9JsFNNKNtWmvRifaOf+cLR+urbZotqk
M0qB+sbjiRk85m9iDr8R85/nr2EXfKN1S/RHFK2dX90QbIqRdHUsNp+kgSIRL/6yHt5y/UW6OhR2y2rA
cX8rDJZHt0x/0sweGbOvqIF9I3UwWA5tuv4m7CFf1Zp+A4xPtEq5kOmzvDR/B+UqJQ1D2j6dFZnxcU3G
+yIdP+gszadi412sq2lGr2cRnxLvnW/9DDrzQwlOScXXklbMgrb0QTQ0f8gxL6/z9fpB3Nvbf4q1jMFy
kOcmcSht4kTSIlbbGzy3ad5Go2vDFf/z+i8AAP//8wVirb4QAAA=
`,
	},

	"/img": {
		name:  "img",
		local: `img`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"img": {
		_escData["/img/appicon.ico"],
	},
}
